# Generated by Django 5.1.5 on 2025-02-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('depoimento', models.TextField(max_length=200)),
                ('foto', models.ImageField(blank=True, upload_to='fotos-depoimentos')),
            ],
        ),
    ]
