# Generated by Django 5.1.5 on 2025-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadaMilhas', '0002_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='foto',
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotos-destinos-1'),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos-destinos-2'),
        ),
        migrations.AddField(
            model_name='destino',
            name='meta',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='destino',
            name='texto_descritivo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
