# Generated by Django 5.1.5 on 2025-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadaMilhas', '0003_remove_destino_foto_destino_foto_1_destino_foto_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='texto_descritivo',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
